[package]
name = "inko"
version = "0.8.1" # VERSION
authors = ["Yorick Peterse <yorick@yorickpeterse.com>"]
edition = "2018"
license = "MPL-2.0"

[lib]
doctest = false

[features]
default = []
jemalloc = ["jemallocator"]
libffi-system = ["libinko/libffi-system"]

[dependencies]
dircpy = "^0.3"
dirs-next = "^1.0"
getopts = "^0.2"
jemallocator = { version = "^0.3", optional = true }
libinko = { path = "../vm" }

[dependencies.git2]
version = "^0.13"
default-features = false
