# frozen_string_literal: true

source 'https://rubygems.org'

gem 'ansi', '~> 1.5'
gem 'rake', '~> 12.0'
gem 'rspec', '~> 3.6'
gem 'rubocop', '~> 0.49'
gem 'rubocop-rspec', '~> 1.15'
gem 'sxdg', '~> 1.0'
