# frozen_string_literal: true

require 'bundler'
require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new(:test) do |task|
  task.verbose = false
end

RuboCop::RakeTask.new(:rubocop)

task default: %i[test rubocop]
