---
name: Build CI container
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the image to build'
        required: true
        type: string
      runner:
        description: 'The host runner to use'
        required: false
        default: ubuntu-24.04
        type: string
      dockerfile:
        description: 'The directory of the Dockerfile to use'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  NAMESPACE: inko-lang/ci

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ci/docker/${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}:${{ inputs.name }}
